#!/usr/bin/env bash
# Get the PID of the 4-to_infinity_and_beyond process
pid=$(pgrep -f 4-to_infinity_and_beyond)

# Check if the process is running and kill it
if [[ -n "$pid" ]]; then
    kill "$pid"
    echo "Process 4-to_infinity_and_beyond (PID: $pid) has been terminated."
else
    echo "No 4-to_infinity_and_beyond process found."
fi

